version: 3

tasks:
  build:
    desc: Builds the binary
    cmds:
      - go get .
      - go build -o hcuc

  changelog:
    desc: Generate Changelog
    cmds:
      - rm -f CHANGELOG.md
      - git-changelog -o CHANGELOG.md -c conventional -t keepachangelog --provider github .

  test:
    desc: Run go test
    cmds:
      - go test ./... -v

  upgrade:
    desc: Update go dependencies
    cmd: go get -u